#!/bin/sh

### BEGIN INIT INFO
# Provides:		application
# Required-Start:	$docker
# Required-Stop:	$docker
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Docker Services
### END INIT INFO

set -e

CMD="cd /home/ec2-user;/usr/local/bin/docker-compose -f docker-compose.yml -f docker-compose-#apptype#.yml"
UPOPTS="-d --no-recreate --no-build --no-deps"

case "$1" in
    start)
        log_daemon_msg "Starting Application" "application" || true
        $CMD $OPTS up $UPOPTS
        ;;

    stop)
        log_daemon_msg "Stopping Application" "application" || true
        $CMD $OPTS stop
        ;;

    reload)
        log_daemon_msg "Reloading Application" "application" || true
        $CMD $OPTS up $UPOPTS
        ;;

    restart)
        docker-compose $OPTS stop
        $CMD $OPTS up $UPOPTS
        ;;

    *)
        log_action_msg "Usage: /etc/init.d/application {start|stop|restart|reload}" || true
        exit 1
        ;;
esac

exit 0
